# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB : santex
    ports:
      - 5432:5432

  # habilitar esto si quieren tener un ambiente en la nube para explorar la base de datos en http://127.0.0.1:8080
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
